### ISSUE TITLE
pricing information empty

### ISSUE THREAD

**Issue by psytraxx** [ilia-semenov/awspricingfull#10]
hi ilia
can you please check if this works for you?

```
ec2pricing.print_table("reserved") #PrettyTable - Reserved Pricing: EC2
```

all the pricy colums are empty in my case

|   us-east-1    |  c4.2xlarge |    linux    |  1   | partialUpfront |       |         |
|   us-east-1    |  c4.2xlarge |    linux    |  3   |   allUpfront   |       |         |
|   us-east-1    |  c4.2xlarge |    linux    |  3   |   noUpfront    |       |         |
|   us-east-1    |  c4.2xlarge |    linux    |  3   | partialUpfront |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  1   |   allUpfront   |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  1   |   noUpfront    |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  1   | partialUpfront |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  3   |   allUpfront   |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  3   |   noUpfront    |       |         |
|   us-east-1    |  c4.4xlarge |    linux    |  3   | partialUpfront |       |         |
|   us-east-1    |  c4.8xlarge |    linux    |  1   |   allUpfront   |       |         |

thank you
Eric

**Comment by ilia-semenov** [comment]
@psytraxx Eric, this is now fixed. The bug was due to introduction of convertible instances and the following change in the AWS back-end db.
