### ISSUE TITLE
RDSPrices.get_ondemand_instances_prices()

### ISSUE THREAD

**Issue by destinymedia** [ilia-semenov/awspricingfull#11]
throws an exception on ca-central-1 region

(as of commit e840bbe)

As a workaround I put a try/except block at line 1862. The following line crashes:

> region_name = self.JSON_NAME_TO_REGIONS_API[r["region"]]

**Comment by ilia-semenov** [comment]
@destinymedia Thank you for pointing at this. I have not been maintaining the project for a while, and every new region (in this case Canada) throws exception unless added to dictionary. I will be working on this this week and plan to fix all the bugs.

**Comment by ilia-semenov** [comment]
The issue is fixed.
