### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by setuk** [ilia-semenov/awspricingfull#4]
Do you have a roadmap for including other AWS components in this tool.
I find it very helpful and would look to extend it to initially cover EBS

**Comment by ilia-semenov** [comment]
There is definitely DynamoDB in the roadmap - I am already working on adding it. EBS will follow next, not sure how soon though.

**Comment by setuk** [comment]
ok thanks.
Keep up the good work - its awesome.
Im surprised there isnt already an offering out there that consumes all AWS JSON pricing files.
Anyone architecting an AWS solution needs to be able to accurately cost it in all aspects and you cant do that without being able to access all the costs easily!
I may have a go at the EBS stuff myself - time is short though!

Cheers

**Comment by setuk** [comment]
I notice you have a field called utilization in the full csv output - which is defaulted to heavy - doesnt come from any AWS JSON file that i can see - what relevance does that have?

**Comment by ilia-semenov** [comment]
@setuk Full CSV is the collection of prices for all services. As you might know, AWS has recently changed their Reservation pricing policies. Basically, now everything is Heavy utilization (no more Medium and Light), and Heavy utilized instances in turn have different payment options ("po" column in output) - NoUpfront, PartialUpfront and AllUpfront.
However, the rollout of the change is kinda slow and for now it covers all the services except ElastiCache. This is the reason why the final output still has the Utilization column - for ElastiCache it is populated from JSON source, and for other services (where utilization gradation does not exist anymore) it is artificially defaulted to Heavy (which does correspond to reality).

**Comment by ilia-semenov** [comment]
Please see https://aws.amazon.com/blogs/aws/new-aws-price-list-api/ for the official AWS pricing API.
