### ISSUE TITLE
Support for other basic AWS services

### ISSUE THREAD

**Issue by jalbstmeijer** [ilia-semenov/awspricingfull#6]
Hi,

It would be great if the following prices could be collected too;
- ec2 and RDS EBS
- ELB
- traffic

Had a quick look at the code, but most is tailored for instance like data.

If you have no time, maybe you can give some pointers (simple class template) that would fit simple non instance like data.
Even though I'm no very good with Python it might be enough to give it a try.

Gr, J

**Comment by ilia-semenov** [comment]
Thank you for your comment. I have decided to pause the development as AWS finally introduced the official pricing API: https://aws.amazon.com/blogs/aws/new-aws-price-list-api/
Please, let me know if it solves your use case. if not, I am happy to continue development.
